const mongoose = require('mongoose');

const weekSchema = new mongoose.Schema({
   week:{
    type:String
   },
    days:{
        type:[
            String
        ]
    },
        day:{
            monday:{
              
                hours:{type:[String],default:[
                    "8AM",
                    "9AM",
                    "10AM",
                    "11AM",
                    "12PM",
                    "1PM",
                    "2PM",
                    "3PM",
                    "4PM",
                    "5PM",
                    "6PM"
                ]},
                active:Boolean
            },
            tuesday:{
                hours:{type:[String],default:[
                    "8AM",
                    "9AM",
                    "10AM",
                    "11AM",
                    "12PM",
                    "1PM",
                    "2PM",
                    "3PM",
                    "4PM",
                    "5PM",
                    "6PM"
                ]},
                active:Boolean
            },
            wenesday:{
                hours:{type:[String],default:[
                    "8AM",
                    "9AM",
                    "10AM",
                    "11AM",
                    "12PM",
                    "1PM",
                    "2PM",
                    "3PM",
                    "4PM",
                    "5PM",
                    "6PM"
                ]},
                active:Boolean
            },
      
        thursday:{
            hours:{type:[String],default:[
                "8AM",
                "9AM",
                "10AM",
                "11AM",
                "12PM",
                "1PM",
                "2PM",
                "3PM",
                "4PM",
                "5PM",
                "6PM"
            ]},
            active:Boolean
        },
 
    friday:{
        hours:{type:[String],default:[
            "8AM",
            "9AM",
            "10AM",
            "11AM",
            "12PM",
            "1PM",
            "2PM",
            "3PM",
            "4PM",
            "5PM",
            "6PM"
        ]},
        active:Boolean
    },
    saturday:{
        hours:{type:[String],default:[
            "8AM",
            "9AM",
            "10AM",
            "11AM",
            "12PM",
            "1PM",
            "2PM",
            "3PM",
            "4PM",
            "5PM",
            "6PM"
        ]},
        active:Boolean
    },
    sunday:{
        hours:{type:[String],default:[
            "8AM",
            "9AM",
            "10AM",
            "11AM",
            "12PM",
            "1PM",
            "2PM",
            "3PM",
            "4PM",
            "5PM",
            "6PM"
        ]},
        active:Boolean
    }

        },
    email:{
        type:String
    }
      
})
module.exports = mongoose.model('week',weekSchema)